# --- Serving options --- #
title: R Users Group - Ecuador
description: Pagina oficial de R Users Group - Ecuador

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
avatar: "/img/final5x5.png"

# List of links in the navigation bar
navbar-links:
#  Próximos eventos:
#    - Conferencia estadística: "conf_stat2018"
   - Jornadas R: "jornadas_r2018"
  R Potencial: "http://rusersgroup.com/blog/R_potencial/"
  Blog R:
    - Temario: "publicaciones"
    - Etiquetas: "tags"
  Servicios:
    - Capacitación permanente: "cursos"
    - Consultoría: "consultoria"
  Nosotros:
    - ¿Quiénes somos?: "about"
    - Contacto: "contact"
  Únete:
    - como miembro: "join"
    - como miembro editor: "join_editor"
    - como Consultor: "consul"


# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: R Users Group - Ecuador
  email: "info@rusersgroup.com"
  facebook: groups/rusersgroup
  github: rusersgroup
  twitter: rusersgroup
  linkedin: "company/24979492"
  #stackoverflow: 
 
# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: false
  
  # Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

disqus: "rusersgroup-com"
google_analytics: "UA-102304043-1"

# Gems
plugins: [jekyll-paginate]

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      show-avatar: true
      comments: true
      social-share: true
      share: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true



# Exclude these files from production site
exclude:
  - CNAME
  - CNAME1
  - LICENSE
  - README.md

